baseURL: "https://jjoshi03.github.io"
languageCode: "en-us"
title: "Janki Joshi"
theme: master

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD
canonifyURLs:  true

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
      #name: Blog
      #title: Blog posts
      #url: /blogs
      #weight: 1

    #Dropdown menu
    #- identifier: dropdown
      #title: Example dropdown menu
      #name: Dropdown
      #weight: 2
    #- identifier: dropdown1
      #title: example dropdown 1
      #name: example 1
      #url: /#
      #parent: dropdown
      #weight: 1
    #- identifier: dropdown2
      #title: example dropdown 2
      #name: example 2
      #url: /#
      #parent: dropdown
      #weight: 2

params:
  #title: "Hugo Profile"
  #description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/J.svg"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark
    color:  
        secondaryBackgroundColor: "Blue"
    # darkmode:
    #     secondaryBackgroundColor: "Blue"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #     textColor: "black"
  #     secondaryTextColor: 
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
      position: absolute
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi there! I'm "
    title: "Janki Joshi"
    #subtitle: 
    content: "I am a highly experienced Software Test engineer with a distinguished track record of over 4 years in Banking software development and testing. I have graduated with Master&rsquo;s in Business Analytics from California State University, East Bay."
    image: "images/me_.jpeg"
    button:
      background - color: 
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1UaSWrDJrOKG1pfLN4uifOi4e7-TMsxej/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/jjoshi03
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/janki-joshi333/
        # - icon: fab fa-instagram
        #   url: https://www.instagram.com/
      #customIcons:
        #- icon: /fav.png
        #  url: "https://example.com"

  # About
  about:
    enable: true
    title: "I'm Open to work from December 2023"
    image: "/images/me1.jpg"
    content:
     I am a highly experienced Software Test engineer with a distinguished track record of over 4 years in Banking software development and testing. I have graduated with Master&rsquo;s in Business Analytics from California State University, East Bay. I take immense satisfaction in meticulously crafting automation testing workflows that are designed to perfection, while consistently adhering to industry-leading frameworks and standards.
     Within my role, I demonstrate excellence in spearheading and orchestrating automation testing projects, covering the entire process from ideation to execution. I showcase an exceptional ability to craft and advance state-of-the-art automation testing frameworks that address a wide range of functional and non-functional testing needs. Additionally, I exhibit a notable proficiency in smoothly incorporating manual testing teams into the automation workflow, leveraging enterprise-level, industry-standard automation test frameworks.
     
    skills:
      enable: true
      title: "Skills:"
      items:
        - "Java, Python, C++, C#, Typescript, Javascript, HTML, CSS"
        - "Selenium webdriver, HP QTP, EggPlant Functional, Protractor, Rest Assured, Cypress, Appium"
        - Postman, Apache Jmeter, Tricentis Flood.IO
        - TestNG, Jasmine, MSTest, Cucumber
        - "MySQL, MongoDB"
        - Azure DevOps, Jira, HP Quality Center, Asana
        - Jenkins, AWS, Device Farm, Git, GitHub, BitBucket
        - Docker, Maven
        - Agile methodologies(Scrum)
        - "Leadership, Adaptability, Cross-Cultural Teamwork, Reliability, Team Player"
       

  # Experience
  experience:
    enable: true
    items: 
      - job: "Software Test Engineer"
        company: "BNP Paribas - eTrading - XIPHIAS"
        companyUrl: "https://www.bnpparibas.co.in/en/"
        date: "Mar 2019 - Jan 2022"
        info:
          enable: true
          content: "Location: Mumbai, India "
        featuredLink:
          enable: false
          url: "https://www.bnpparibas.co.in/en/"
        info:
          content: "Worked as a Software Test Engineer at BNP Paribas - eRates"
        content: |-
          Mumbai, India
          - Designed and implemented a scalable automation framework utilizing Selenium WebDriver, Rest-Assured, Java, Maven, TestNG, and Cucumber, significantly reducing testing time and improving test coverage.
          - Developed 100+ end-to-end trade test cases using Selenium and HP UFT for an eTrading application, enhancing defect detection rates and test reliability.
          - Led the migration of 400+ test cases from the UI Testing tool, Eggplant Functional, to Selenium, resulting in substantial cost savings. Recognized as the best performer for optimizing testing processes.
          - Collaborated closely with developers and design teams, proactively identifying and reporting issues and defects to ensure their timely resolution and the delivery of a high-quality product.
          - Automated a mobile application testing framework using Appium, seamlessly integrating it with AWS Device Farm for the streamlined execution of 200+ test cases.
          - Mentored and guided 3 interns on Agile methodologies, JIRA usage, and domain-specific knowledge, fostering their professional development and enabling impactful contributions.
          

      - job: "Associate Software Test Engineer"
        company: "BNP Paribas - eTrading - AGATA"
        companyUrl: "https://www.bnpparibas.co.in/en/"
        date: "June 2017 - Feb 2019"
        info:
          enable: true
          content: "Location: Mumbai, India "
        featuredLink:
          enable: false
          url: "https://www.bnpparibas.co.in/en/"
        info:
          content:
        content: |-
          Mumbai, India
          - Developed a performance test suite using Apache JMeter to actively monitor microservices, leading to swift issue identification and improved system response time under high load conditions.
          - Conducted functional, regression, sanity, and smoke testing before release, analyzed results, and delivered comprehensive reports globally.
          - Automated REST API checks using Postman, ensuring usability and correctness and resulting in significant time savings.
          - Strategized and implemented the delivery pipeline by streamlining CI/CD workflows through seamless integration of Jenkins, Bitbucket, and Jira, resulting in accelerated software delivery cycles.
          - Designed and implemented Selenium WebDriver frameworks with TestNG and Java, focusing on ETL performance optimization for enhanced reliability in XML file handling.
          - Executed the complete SDLC cycle, demonstrating expertise in test planning, design, and execution, contributing to improved testing efficiency and reduced time.

      - job: "Software Engineer Intern"
        company: "Prarambhan Pvt. ltd"
        companyUrl: "https://www.thecompanycheck.com/company/prarambhan-entertainment-private-limited/U92412MH2015PTC269465"
        date: "Mar 2016 - May 2016"
        info:
          enable: true
          content: "Location: Mumbai, India"
        featuredLink:
          enable: false
          url: "https://www.thecompanycheck.com/company/prarambhan-entertainment-private-limited/U92412MH2015PTC269465"
        info:
          content:
        content: |-
          Mumbai, India
          - Collaborated with the DevOps team to address CI/CD issues, ensuring smooth release cycles and conducting thorough JUnit testing to identify and fix bugs for high-quality software delivery.
          - Utilized Docker to containerize application components, improving DevOps practices and ensuring seamless and consistent deployments.
          - Demonstrated proficiency in Maven and Gradle for optimized dependency management and streamlined builds, resulting in a 30% reduction in build times and enhanced productivity.
          - Employed Jenkins as a CI/CD tool and automated deployments to facilitate efficient software releases.


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Masters in Business Analytics"
        school:
          name: "California State University - East Bay"
          url: "https://www.csueastbay.edu/"
        date: "2022 - 2023"
        GPA: "3.6 out of 4.0"
        content: |-
            - Worked as a Computer Science Tutor at SCAA (Student Center for Academic Achievement) department where I empowered students to master OOPM (Java, C++) and guided them in efficient DSAA problem-solving.
            - Worked as a Student Assistant Analyst for Shipping & Receiving department where I managed and analyzed shipment data, ensuring accurate and timely deliveries.
            - Course Work: Big Data Technologies, Database Management, Data Analytics, Data Warehousing, Project Management
      - title: "Bachelor of Engineering in Information Technology"
        school:
          name: "Mumbai University- D.J. Sanghvi College of Engineering"
          url: "https://www.djsce.ac.in/"
        date: "2013 - 2017"
        GPA: "7.38 out of 10"
        content: |-
          - Course Work: Data Structures & Algorithms, Software Engineering, Operating System, Web Technologies, Artificial Intelligence, Cloud Computing


  #featuredLink:
  #enable: true
  #name: "My academic record"
  #url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      #- title: Smart India Hackathon 2020
       # content: Won 2nd place in Smart India Hackathon 2020 for developing a Smart Yoga Instructor with feedback using Deep Learning
        #url: "https://www.sih.gov.in"
      - title: BNP PARIBAS BRAVO SPOT AWARD- 2021
        content: Recognized as the top performer for successfully transitioning from a licensed tool to an open-source alternative, resulting in an annual cost savings of $22K.
        url: "https://drive.google.com/file/d/1m5Ikdj6tivEQdDMW1eEu39Yt4IzuSQDw/view?usp=sharing"

      - title: BNP PARIBAS BRAVO SPOT AWARD- 2018
        content: Awarded as the best performer for reducing manual efforts of 2 hr/day by automating the morning checks in August 2018
        url: "https://drive.google.com/file/d/1g9xwyNOMkCvoEimObSqn_FEO5B7KukdS/view?usp=sharing"

      - title: Certified Indian Classical Dancer
        content: Achieved proficiency in Indian classical dance through seven years of dedicated training.
        url: "https://drive.google.com/file/d/1of3UoLVBq_qJfZ8NuChNg5t_p2wFQMVP/view?usp=sharing"

      - title: Recommendation by Francois Ogliaro
        content: I worked for about 4.5 years with Janki while she was at TCoE BNPP in quality of software tester for the Rates eTrading platform. Rapidly after joining Janki became a go-to person due to her broad range of skills (inc. software development) and easy contact. Soon she single-handed managed complex tasks such as technology migration and full application regression. In addition Janki has a quite and natural authority which draws respect from all colleagues. Overall and due to her attitude and professionalism I am convinced that Janki will fit and do well in pretty much any set up and any role.
        url: "https://www.linkedin.com/in/francois-ogliaro-0493858/"

      - title: Recommendation by Surbhi Sinha
        content: Janki has worked with me at BNP Paribas in Trading domain. She is very knowledgeable and dedicated professional who is willing to go an extra mile for success of the project. Finding a team player and individual contributor like her is really an asset for every organization and team. Her friendly and positive attitude allowed us to share a good bond. It was great pleasure to work with her and I wish her all the success in her future endeavors.
        url: "https://www.linkedin.com/in/surbhi-s-3489a04a/"


  # projects
  projects:
    enable: true
    items:
      - title: Web application automation framework - TDD
        content: This is hybrid automation framework which uses page object model and data-driven framework concepts. This can be used for small application to large applications. This follows Test Driven Development approach. Features - Common utilities, report integration, logger integration, test data management, cross browser testing
        image: /images/projects/Project1-Selenium-TDD.png
        # featured:
        #   name: Click here to know more!
        #   link: https://github.com/jjoshi03/Selenium-AUT-Framework
        badges:
          - "Selenium-webdriver"
          - "TestNG"
          - "Java"
          - "Maven"
          - "Extent-report"
        links:
          #- icon: fa fa-envelope
          #  url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/Jjoshi03/Selenium-Using-Java
          # - icon: fab fa-twitter
          #  url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Web application automation framework - BDD
        content: This is hybrid automation framework which uses page object model and behaviour-driven framework concepts. This can be used for small application to large applications.  Features - Common utilities, feature files, report integration, logger integration, test data management, cross browser testing
        image: /images/projects/Project2-Selenium-BDD.png
        featured:
          # name: Click here to know more!
          # link: https://github.com/jjoshi03/BDD_AUT_Framework
        badges:
          - "Selenium-webdriver"
          - "Cucumber"
          - "TestNG"
          - "Java"
          - "Maven"
          - "Extent-report"
        links:
          - icon: fab fa-github
            url: https://github.com/Jjoshi03/BDD-Automation-Framework

      - title: Web application automation - Protractor
        content: This is hybrid automation framework. This can be used to automate application developed using js based frontend frameworks like angular/reactjs to handle asynchronous behaviour properly.
        image: /images/projects/Project3-Protractor.png
        # featured:
        #   name: Click here to know more!
        #   link: https://github.com/jjoshi03/Protractor-AUT-Framework
        badges:
          - "Protractor"
          - "Jasmine"
          - "Typescript"
          - "Nodejs"
          - "Angular"
        links:
          - icon: fab fa-github
            url: https://github.com/Jjoshi03/Protractor-Automation-Framework



  #Contact
  contact:
    enable: true
    content: Feel free to drop me a message anytime! Whether you've got a question or just want to say hi, I'll do my best to get back to you!
    email: jankikjoshi1995@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/jjoshi03
      linkedin: https://www.linkedin.com/in/janki-joshi333/
    # twitter: https://twitter.com
      # instagram: https://www.instagram.com/
    # facebook: https://facebook.com
